User story 1.3
Marko-Shevchuk/testing_automation pull request #14
Opened 2023-10-10 18:29 UTC by Stepan0806

Added user story 1.3, its description and given-when-then acceptance criteria to user_stories.md

2023-10-12 12:52 UTC, Marko-Shevchuk commented
Minor spelling mistakes/inconsistencies: 
* in line "On the "My Account" subpage user can view their contact information...": "user" is to be replaced with "users"
* in all lines containing "side menu": "side menu" might be better generalized as "account navigation menu"
* in line "When: The user clicks on the "Add Payment Method" button and provides the necessary payment information.": possible types of payment methods are not spicified, is another user story for electronic payment required?

2023-10-12 13:01 UTC, Marko-Shevchuk commented on magento/user_stories.md
> +- The profile page should contain links to several subpages in the side menu: "My Account",
"side menu" -> "account navigation menu" ?

2023-10-12 13:04 UTC, Marko-Shevchuk approved these changes
Insignificant spelling mistake

2023-10-12 13:04 UTC, Marko-Shevchuk commented on magento/user_stories.md
> +- On the "My Account" subpage user can view their contact information and change their password, default billing address, or default shipping address.
Count change "user" to "users"

2023-10-12 15:22 UTC, Marko-Shevchuk requested changes

2023-10-12 15:22 UTC, Marko-Shevchuk commented on magento/user_stories.md
> +### Scenario 1.3c - Change account information:
Add negative scenarios to 1.3c, 1.3d, 1.3e, 1.3h and others that need a negative counterpart

2023-10-12 17:07 UTC, Stepan0806 commented
Added negative scenarios

2023-10-13 15:22 UTC, Marko-Shevchuk commented on magento/user_stories.md
> +- On the "Adress Book" subpage user can add addresses and choose the default billing address and default shipping address.
Address

2023-10-13 15:22 UTC, Marko-Shevchuk commented on magento/user_stories.md
> +"My Orders", "My Downloadable Products", "My Wish List", "Address Book", "Account Information" "Stored Payment Methods", "My Product Reviews"
"Account Information" "Stored Payment Methods",

2023-10-13 15:25 UTC, Marko-Shevchuk commented on magento/user_stories.md
> +**Then**: Corresponding field is marked with message "invalid input"
Each corresponding field

2023-10-13 15:25 UTC, Marko-Shevchuk approved these changes

2023-10-15 12:26 UTC, merged