Added user story 1.1
Marko-Shevchuk/testing_automation pull request #15
Opened 2023-10-10 19:30 UTC by Marko-Shevchuk

User story 1.1 repurposed to be "Register" user story, as child of "Account system" epic. Describes user registration.

2023-10-12 17:19 UTC, Stepan0806 requested changes

2023-10-12 17:19 UTC, Stepan0806 commented on magento/user_stories.md
> +**Then**: An error message regarding the existing account is displayed.
Given-when-then construction is displayed in one line. Adding newline symbols is needed

2023-10-17 13:10 UTC, Marko-Shevchuk commented on magento/user_stories.md
> +**Then**: An error message regarding the existing account is displayed.
Double spaces at the end of lines count as newline symbols. Reformat to newlines?

2023-10-17 13:18 UTC, Stepan0806 commented on magento/user_stories.md
> +**Then**: An error message regarding the existing account is displayed.
Yes

2023-10-17 15:34 UTC, Marko-Shevchuk commented on magento/user_stories.md
> +**Then**: An error message regarding the existing account is displayed.
All other docs have been reformatted to double-space, do I leave this as-is?

2023-10-17 15:41 UTC, Stepan0806 commented on magento/user_stories.md
> +**Then**: An error message regarding the existing account is displayed.
I've already fixed it

2023-10-17 15:48 UTC, Stepan0806 approved these changes

2023-10-17 15:48 UTC, merged